search = _{ soi ~ expression ~ eoi }

expression = { (
  logic |
  quote |
  group |
  id |
  pair |
  word
)+ }

logic = _{ logic_and | logic_not | logic_or }
quote = @{ "\"" ~ (!"\"" ~ any)* ~ "\"" }
group = { "(" ~ expression? ~ ")" }
id = @{ "#" ~ ('0'..'9')+ }
pair = ${ key ~ "=" ~ value }

logic_and = @{ "and" }
logic_not = @{ "not" }
logic_or = @{ "or" }

word = @{ (!(" " | "(" | ")") ~ any)+ }
key = @{ (!(" " | "(" | ")" | "=") ~ any)+ }
value = @{ word }


whitespace = _{ " " }
